# Generated by Selenium IDE
import time
import json
import sys
import re
import os
import random
import csv

from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium import webdriver
import selenium


# from dotenv import load_dotenv
# load_dotenv()

name = 'linkedin'

rootDir = os.path.realpath('.')
print(rootDir)
readDir = os.path.join(rootDir, 'import.csv')
writeDir = os.path.join(rootDir, 'export.csv')
USER_NAME = 'avan.miller.1988@gmail.com' #os.getenv('USER_NAME')
PASSWORD = 'projecto!' #os.getenv('PASSWORD')
def randTime():
        return (random.randrange(1000)*(0.001))

levels = ['chief', 'vp', 'vice president', 'director', 'vice']

rolesNeedLevels = ['strategy', 'lending', 'operations', 'technology', 'wealth', 'information', 'executive']
rolesNoLevels = ['innovation']

#init driver
driver = webdriver.Chrome(os.path.join(rootDir, 'chromedriver'))

driver.set_window_size(1440, 700)

#login to LinkedIn
driver.get('https://www.linkedin.com/')
driver.find_element(By.NAME, 'session_key').send_keys(USER_NAME)
driver.find_element(By.NAME, 'session_password').send_keys(PASSWORD)
driver.find_element(By.CSS_SELECTOR, '.sign-in-form__submit-btn').click()

time.sleep(1)

salesNavLink = 'https://www.linkedin.com/sales/search/people/list/employees-for-account/19268?seniority=6%2C7%2C8'

driver.get(salesNavLink)

time.sleep(1)

def vetRole(role):
        for roleNoLevels in rolesNoLevels:
                if (roleNoLevels in role):
                        return True
        for roleNeedLevels in rolesNeedLevels:
                if (roleNeedLevels in role):
                        for level in levels:
                                if (level in role):
                                        return True
        return False

with open('export.csv', mode='w') as outputFile:
        writer = csv.writer(outputFile, delimiter=',', quotechar='"')
        for i in range(20):
                print('next page')
                time.sleep(1)
                for y in range(8):
                        html = driver.find_element_by_tag_name('html')
                        html.send_keys(Keys.END)
                leads = driver.find_elements(By.CLASS_NAME, 'search-results__result-item')
                for lead in leads:
                        # print(lead.get_attribute("innerText"))
                        name = lead.find_element(By.CLASS_NAME, 'result-lockup__name').get_attribute('innerText')
                        print(name)
                        role = lead.find_element(By.CLASS_NAME, 'result-lockup__highlight-keyword').get_attribute('innerText').replace('Go to Valley National Bank account page', '')
                        print('\t' + role)
                        if (vetRole(role.lower())):
                                print('\ttrue')
                                writer.writerow([name, role])
                time.sleep(3)
                driver.find_element(By.CLASS_NAME, 'search-results__pagination-next-button').click()


# company search
# with open(writeDir, mode='w') as outputFile:
#         writer = csv.writer(outputFile, delimiter=',', quotechar='"',)
#         with open(readDir, mode='r') as inputFile:
#                 reader = csv.reader(inputFile, delimiter=',', quotechar='"',)
#                 for row in reader:
#                         time.sleep(1 + randTime())
#                         if (row):
#                                 companyName = row[0]


# driver.close()